### ISSUE TITLE
Please remove common lib/... too.

### ISSUE THREAD

**Issue by GermanBluefox** [iobroker-community-adapters/ioBroker.enigma2#4]

**Comment by Matten-Matten** [comment]
im Moment ist der Adapter durch den Änderungen nicht mehr installierbar!?

```
$ ./iobroker url "https://github.com/Matten-Matten/ioBroker.enigma2.git"
install https://github.com/Matten-Matten/ioBroker.enigma2/tarball/master
npm install https://github.com/Matten-Matten/ioBroker.enigma2/tarball/master --production --save --prefix "C:/ioBroker" (System call)
got C:/ioBroker/node_modules/iobroker.enigma2/admin
upload [12] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/index_m.html index_m.html text/html
upload [11] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/index.html index.html text/html
upload [10] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/ru/translations.json i18n/ru/translations.json application/json
upload [9] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/pt/translations.json i18n/pt/translations.json application/json
upload [8] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/nl/translations.json i18n/nl/translations.json application/json
upload [7] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/it/translations.json i18n/it/translations.json application/json
upload [6] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/fr/translations.json i18n/fr/translations.json application/json
upload [5] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/es/translations.json i18n/es/translations.json application/json
upload [4] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/en/translations.json i18n/en/translations.json application/json
upload [3] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/i18n/de/translations.json i18n/de/translations.json application/json
upload [2] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/enigma2.png enigma2.png image/png
upload [1] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/COMMAND COMMAND application/octet-stream
upload [0] enigma2.admin C:/ioBroker/node_modules/iobroker.enigma2/admin/beispiel.png beispiel.png image/png
ERROR: module.js:590
    throw err;
    ^

SyntaxError: C:\ioBroker\node_modules\iobroker.enigma2\io-package.json: Unexpected token } in JSON at position 907
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:587:27)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Upload.uploadAdapter (C:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupUpload.js:219:23)
    at C:\ioBroker\node_modules\iobroker.js-controller\lib\setup.js:748:44
    at Timeout.upload [as _onTimeout] (C:\ioBroker\node_modules\iobroker.js-controller\lib\setup\setupUpload.js:287:57)

ERROR: process exited with code 1
```

**Comment by Matten-Matten** [comment]
Fehler gefunden.
![_new 1 - notepad -18 08 2018_02_51_47](https://user-images.githubusercontent.com/32074970/44294059-0786cd80-a292-11e8-9364-e1ea088d3237.png)

hab das Komma weg genommen, dann ging es.

**Comment by Matten-Matten** [comment]
wenn ich den **_lib_** Ordner lösche, funktioniert aber der Adapter nicht mehr.

**Comment by Matten-Matten** [comment]
alles entfernt außer die **_utils.js_**
