### ISSUE TITLE
unhandled promise rejection - js-controller 3.2.2

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.enigma2#45]
Node 14.15.1, lxc debian 10, js-controller 3.2.2:

`2021-01-09 10:59:15.278  - info: enigma2.0 (4244) starting. Version 1.3.2 in /opt/iobroker/node_modules/iobroker.enigma2, node: v14.15.4, js-controller: 3.2.2
2021-01-09 10:59:15.300  - info: enigma2.0 (4244) starting Polling every 10000 ms
2021-01-09 10:59:15.318  - error: enigma2.0 (4244) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-01-09 10:59:15.318  - error: enigma2.0 (4244) unhandled promise rejection: Not exists
2021-01-09 10:59:15.320  - error: enigma2.0 (4244) Error: Not exists
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2270:17)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3010:38)
    at processImmediate (internal/timers.js:463:21)
2021-01-09 10:59:15.321  - error: enigma2.0 (4244) Not exists
2021-01-09 10:59:15.322  - error: enigma2.0 (4244) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-01-09 10:59:15.323  - error: enigma2.0 (4244) unhandled promise rejection: Not exists
2021-01-09 10:59:15.323  - error: enigma2.0 (4244) Error: Not exists
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2270:17)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3010:38)
    at processImmediate (internal/timers.js:463:21)
2021-01-09 10:59:15.323  - error: enigma2.0 (4244) Not exists
2021-01-09 10:59:15.328  - error: enigma2.0 (4244) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-01-09 10:59:15.328  - error: enigma2.0 (4244) unhandled promise rejection: Not exists
2021-01-09 10:59:15.328  - error: enigma2.0 (4244) Error: Not exists
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2270:17)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3010:38)
    at processImmediate (internal/timers.js:463:21)
2021-01-09 10:59:15.329  - error: enigma2.0 (4244) Not exists
2021-01-09 10:59:15.329  - error: enigma2.0 (4244) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-01-09 10:59:15.330  - error: enigma2.0 (4244) unhandled promise rejection: Not exists
2021-01-09 10:59:15.330  - error: enigma2.0 (4244) Error: Not exists
    at Object.maybeCallbackWithError (/opt/iobroker/node_modules/iobroker.js-controller/lib/tools.js:2270:17)
    at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3010:38)
    at processImmediate (internal/timers.js:463:21)
2021-01-09 10:59:15.330  - error: enigma2.0 (4244) Not exists
2021-01-09 10:59:15.839  - info: enigma2.0 (4244) terminating
2021-01-09 10:59:15.840  - warn: enigma2.0 (4244) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-01-09 10:59:17.082  - error: host.VMC123-iobroker instance system.adapter.enigma2.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
`

**Comment by Apollon77** [comment]
will be fixed by js.controller later

**Comment by Apollon77** [comment]
fixed with js-controller 3.2.4
